#!/usr/bin/env python3
"""
Report template renderer — Generates markdown daily digest
"""

from datetime import datetime
from typing import List, Dict

def render_report(
    summaries: List[Dict],
    date: str,
    search_query: str
) -> str:
    """
    Render full daily report in markdown format.
    """
    
    # Count categories
    category_counts = {}
    for s in summaries:
        cat = s.get('category', 'Infrastructure')
        category_counts[cat] = category_counts.get(cat, 0) + 1
    
    # Count actionability
    actionability_counts = {'high': 0, 'medium': 0, 'low': 0}
    for s in summaries:
        act = s.get('actionability', 'medium').lower()
        actionability_counts[act] = actionability_counts.get(act, 0) + 1
    
    # Build report
    report = f"""# AI Pulse Report — {date}

**Search Query:** {search_query}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')} (Europe/Paris)
**Sources:** {len(summaries)} videos analyzed

---

## 🏆 Top 10 AI Stories (Ranked)

"""
    
    # Top 10 stories
    for i, summary in enumerate(summaries, 1):
        report += render_story(i, summary)
    
    # Trending topics
    report += f"""
---

## 📊 Trending Topics (Today)

**Category Breakdown:**
"""
    for cat, count in sorted(category_counts.items(), key=lambda x: x[1], reverse=True):
        report += f"- **{cat}:** {count} stories\n"
    
    report += f"""
**Actionability Distribution:**
- 🔥 **High:** {actionability_counts['high']} (build this week)
- ⚡ **Medium:** {actionability_counts['medium']} (adapt with effort)
- 📖 **Low:** {actionability_counts['low']} (conceptual only)

---

## 🧠 Category Highlights

"""
    
    # Category-specific highlights
    for category in ['Local LLM', 'Multi-Agent', 'Models', 'Infrastructure']:
        cat_videos = [s for s in summaries if s.get('category', '').lower() == category.lower()]
        if cat_videos:
            report += f"""### {category}
{render_category_summary(cat_videos)}

"""
    
    report += f"""
---

## 📈 Sources Breakdown

- **Videos processed:** {len(summaries)}
- **Search query:** "{search_query}"
- **Transcripts fetched:** {len(summaries)}
- **Credits used:** 30 (20 search + 10 transcripts)

---

## 📝 Obsidian Links

"""
    
    for i, summary in enumerate(summaries, 1):
        short_id = f"AI-{date}-{i:02d}"
        report += f"- [[{short_id}]] — {summary.get('title', 'Unknown')}\n"
    
    report += f"""
---

*Report generated by AI Pulse Tracker skill — OpenClaw*
"""
    
    return report

def render_story(i: int, summary: Dict) -> str:
    """Render a single story entry."""
    
    title = summary.get('title', 'Unknown')
    channel = summary.get('channel', 'Unknown')
    # Handle dict channel format from API
    channel_name = channel.get('title', str(channel)) if isinstance(channel, dict) else str(channel)
    category = summary.get('category', 'TBD')
    url = summary.get('url', '')
    tl_dr = summary.get('summary', {}).get('tl_dr', 'No summary')
    actionability = summary.get('summary', {}).get('actionability', 'medium')
    homelab = summary.get('summary', {}).get('homelab_friendly', False)
    
    actionability_emoji = {
        'high': '🔥',
        'medium': '⚡',
        'low': '📖'
    }.get(actionability.lower() if actionability else 'medium', '⚡')
    
    homelab_badge = "🏠 Homelab-friendly" if homelab else ""
    
    return f"""### #{i} — {title}

- **Category:** {category}
- **Source:** {channel_name}
- **Actionability:** {actionability_emoji} {actionability.title() if actionability else 'Medium'}
{homelab_badge}
- **TL;DR:** {tl_dr}
- **Link:** [Watch]({url})

---

"""

def render_category_summary(videos: List[Dict]) -> str:
    """Render category-specific summary."""
    
    if len(videos) == 0:
        return "No stories in this category today."
    
    insights = []
    for v in videos:
        v_insights = v.get('summary', {}).get('key_insights', [])
        if v_insights:
            insights.extend(v_insights[:2])
    
    if insights:
        return f"**Key Insights:**\n" + "\n".join(f"- {ins}" for ins in insights[:3])
    else:
        return f"**Featured:** {len(videos)} stories — see Top 10 list above"
